services:
  ########################################################################
  # Join node
  ########################################################################
  node:
    image: 172.18.114.101:5556/decentralized-ai/inferenced:0.0.1-multimodels-2
    command: ["sh", "./init-docker.sh"]
    environment:
      - KEY_NAME=${KEY_NAME}
      - SEED_NODE_RPC_URL=${SEED_NODE_RPC_URL}
      - SEED_NODE_P2P_URL=${SEED_NODE_P2P_URL}
      - TRUSTED_BLOCK_PERIOD=${TRUSTED_BLOCK_PERIOD:-2000}
    volumes:
      - join-data:/root/.inference
    networks:
      - dai-network
      - internal
    ports:
      - target: 26656
        published: 26656
        protocol: tcp
        mode: host
      - target: 26657
        published: 26657
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.${NODE_LABEL} == true
    depends_on:
      - inference

  ########################################################################
  # Join API
  ########################################################################
  api:
    image: 172.18.114.101:5556/decentralized-ai/api:0.0.1-multimodels-2
    depends_on:
      - node
    environment:
      - KEY_NAME=${KEY_NAME}
      - DAPI_API__POC_CALLBACK_URL=${POC_CALLBACK_URL}
      - DAPI_API__PUBLIC_URL=${PUBLIC_URL}
      - DAPI_CHAIN_NODE__SEED_API_URL=${SEED_API_URL}
      - DAPI_CHAIN_NODE__URL=http://node:26657
      - NODE_CONFIG_PATH=/root/node_config.json
    volumes:
      - join-data:/root/.inference
    networks:
      - dai-network
      - internal
    ports:
      - target: 8080
        published: 8000
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.${NODE_LABEL} == true
    configs:
      - source: node_config
        target: /root/node_config.json

  ########################################################################
  # Join Inference
  ########################################################################
  inference:
    image: 172.18.114.101:5556/decentralized-ai/mlnode:3.0.1-alpha1
    command: >
      uvicorn api.app:app
      --host=0.0.0.0
      --port=8080
    environment:
      - HF_HOME=/root/.cache
    volumes:
      - type: bind
        source: /home/gm/cache
        target: /root/.cache
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.${NODE_LABEL} == true
          - node.labels.gpu == true
    networks:
      - internal

volumes:
  join-data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=524288000

configs:
  node_config:
    file: ./node-config.json

networks:
  dai-network:
    external: true
  internal: {}