version: "3.8"

volumes:
  genesis-data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=524288000

services:
  ########################################################################
  # GENESIS GROUP
  ########################################################################
  node:
    image: 172.18.114.101:5556/decentralized-ai/inferenced:0.0.1-multimodels-1
    command: ["sh", "./init-docker-genesis.sh"]
    environment:
      - KEY_NAME=genesis
      - SNAPSHOT_INTERVAL=1000
      - SNAPSHOT_KEEP_RECENT=5
    volumes:
      - genesis-data:/root/.inference
      - ./genesis-overrides.json:/root/genesis_overrides.json
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.genesis == true
    ports:
      - target: 26656
        published: 26656
        protocol: tcp
        mode: host
      - target: 26657
        published: 26657
        protocol: tcp
        mode: host
    depends_on:
      - inference
    networks:
      - dai-network
      - genesis-network

  api:
    image: 172.18.114.101:5556/decentralized-ai/api:0.0.1-multimodels-1
    depends_on:
      - node
    environment:
      - KEY_NAME=genesis
      - DAPI_API__POC_CALLBACK_URL=http://api:8080
      - DAPI_API__PUBLIC_URL=http://genesis_api:8080
      - DAPI_CHAIN_NODE__IS_GENESIS=true
      - DAPI_CHAIN_NODE__URL=http://node:26657
      - NODE_CONFIG_PATH=/root/node_config.json
    volumes:
      - genesis-data:/root/.inference
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.genesis == true
    ports:
      - target: 8080
        published: 8000
        protocol: tcp
        mode: host
    configs:
      - source: node_config
        target: /root/node_config.json
    networks:
      - dai-network
      - genesis-network

  inference:
    image: 172.18.114.101:5556/decentralized-ai/mlnode:3.0.1-alpha1
    command: >
      uvicorn api.app:app
      --host=0.0.0.0
      --port=8080
    environment:
      - HF_HOME=/root/.cache
    volumes:
      - type: bind
        source: /home/gm/cache
        target: /root/.cache
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.genesis == true
          - node.labels.gpu == true
    networks:
      - genesis-network

configs:
  node_config:
    file: ./node-config.json

networks:
  dai-network:
    external: true
  genesis-network:
    driver: overlay
    attachable: true