apiVersion: v1
kind: Service
metadata:
  name: api-private # RENAMED from api-internal
  labels:
    app: api
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
  - name: ml-server
    port: 9100
    targetPort: 9100 # Assuming api-deployment.yaml containerPort is 9100 (or named ml-api which resolves to 9100)
  - name: admin
    port: 9200
    targetPort: 9200 # Assuming api-deployment.yaml containerPort is 9200 (or named admin-api which resolves to 9200) 