apiVersion: v1
kind: Service
metadata:
  name: api-public
  labels:
    app: api
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
  - name: public
    port: 9000
    targetPort: 9000
  externalIPs:
  - "34.9.136.116"
