apiVersion: v1
kind: Service
metadata:
  name: api # Or api-internal, depending on your preferred internal DNS name
  labels:
    app: api
spec:
  type: ClusterIP # Default, but explicit for clarity
  selector:
    app: api
  ports:
  - name: ml-server # Matches the name from your modified common api-service
    port: 9100
    targetPort: ml-api # Assumes container port in api-deployment is named 'ml-api'
  - name: admin # Matches the name from your modified common api-service
    port: 9200
    targetPort: admin-api # Assumes container port in api-deployment is named 'admin-api' 