apiVersion: v1
kind: Service
metadata:
  name: api
  # namespace: will be applied by kubectl -n or overlay
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
  - name: public-api
    port: 9000      # Service port for public API
    targetPort: public-api
  - name: ml-api
    port: 9100      # Service port for ML API / poc_callback
    targetPort: ml-api
  - name: admin-api
    port: 9200      # Service port for Admin API
    targetPort: admin-api
  # type: ClusterIP # Default. For external access to public-api (9000), consider LoadBalancer or Ingress. 