apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  type: NodePort
  selector:
    app: api
  ports:
  - name: public
    port: 9000
    targetPort: 9000
    nodePort: 30002 # Expose to the outer world
  - name: ml-server
    port: 9100
    targetPort: 9100
  - name: admin
    port: 9200
    targetPort: 9200
