apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-public-service.yaml
  - api-private-service.yaml
  - node-service.yaml
  - inference-service.yaml

  # Common ConfigMaps
  - node-configs/node-config-configmap.yaml
