apiVersion: v1
kind: Service
metadata:
  name: node
  labels:
    app: node
spec:
  type: ClusterIP
  selector:
    app: node
  ports:
  - name: tendermint-p2p
    port: 26656
    targetPort: 26656
  - name: tendermint-rpc
    port: 26657
    targetPort: 26657
  externalIPs:
  - "34.9.136.116"
