version: "3.8"

volumes:
  genesis-data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=524288000
  join-data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=524288000

services:
  ########################################################################
  # GENESIS GROUP (fixed 3 containers, pinned to genesis=true)
  ########################################################################
  genesis-node:
    image: 172.18.114.101:5556/decentralized-ai/inferenced:0.0.1-alpha3
    command: ["sh", "./init-docker-genesis.sh"]
    environment:
      - KEY_NAME=genesis
      - SNAPSHOT_INTERVAL=1000
      - SNAPSHOT_KEEP_RECENT=5
    volumes:
      - genesis-data:/root/.inference
      - ./genesis-overrides.json:/root/genesis_overrides.json
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.genesis == true
    ports:
      - "26656:26656"   # p2p
      - "26657:26657"   # rpc

    depends_on:
      - genesis-inference
    networks:
      - dai-network

  genesis-api:
    image: 172.18.114.101:5556/decentralized-ai/api:0.0.1-alpha3
    depends_on:
      - genesis-node
    environment:
      - KEY_NAME=genesis
      - DAPI_API__POC_CALLBACK_URL=http://genesis-api:8080
      - DAPI_API__PUBLIC_URL=http://genesis-api:8080
      - DAPI_CHAIN_NODE__IS_GENESIS=true
      - DAPI_CHAIN_NODE__URL=http://genesis-node:26657
      - NODE_CONFIG_PATH=/root/node_config.json
    volumes:
      - genesis-data:/root/.inference
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.genesis == true
    ports:
      - "8000:8080"
    configs:
      - source: node_config_genesis
        target: /root/node_config.json
    networks:
      - dai-network

  genesis-inference:
    image: 172.18.114.101:5556/decentralized-ai/mlnode:3.0.1-alpha1
    command: >
      uvicorn api.app:app
      --host=0.0.0.0
      --port=8080
    environment:
      - HF_HOME=/root/.cache
    volumes:
      - type: bind
        source: /home/gm/cache
        target: /root/.cache
    networks:
      - dai-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.genesis == true
          - node.labels.gpu == true

  ########################################################################
  # JOIN GROUP (3 "global" services) => 1 group per labeled node
  ########################################################################
  join-node:
    image: 172.18.114.101:5556/decentralized-ai/inferenced:0.0.1-alpha3
    command: ["sh", "./init-docker.sh"]
    environment:
      - KEY_NAME=join-1
      - SEED_NODE_RPC_URL=http://genesis-node:26657
      - SEED_NODE_P2P_URL=http://genesis-node:26656
      - TRUSTED_BLOCK_PERIOD=2000
    volumes:
      - join-data:/root/.inference
    networks:
      - dai-network
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.join == true

    depends_on:
      - genesis-node
      - join-inference

  join-api:
    image: 172.18.114.101:5556/decentralized-ai/api:0.0.1-alpha3
    depends_on:
      - join-node
    environment:
      - KEY_NAME=join-1
      - DAPI_API__POC_CALLBACK_URL=http://join-api:8080
      - DAPI_API__PUBLIC_URL=http://join-api:8080
      - DAPI_CHAIN_NODE__SEED_API_URL=http://genesis-api:8080
      - DAPI_CHAIN_NODE__URL=http://join-node:26657
      - NODE_CONFIG_PATH=/root/node_config.json
    volumes:
      - join-data:/root/.inference
    networks:
      - dai-network
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.join == true
    configs:
      - source: node_config_join
        target: /root/node_config.json

  join-inference:
    image: 172.18.114.101:5556/decentralized-ai/mlnode:3.0.1-alpha1
    command: >
      uvicorn api.app:app
      --host=0.0.0.0
      --port=8080
    environment:
      - HF_HOME=/root/.cache
    volumes:
      - type: bind
        source: /home/gm/cache
        target: /root/.cache
    networks:
      - dai-network
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.join == true
          - node.labels.gpu == true


configs:
  node_config_genesis:
    file: ./node-config_genesis.json
  node_config_join:
    file: ./node-config_join.json

networks:
  dai-network:
    driver: bridge
