version: "3.7"

services:
  node:
    container_name: node
    image: gcr.io/decentralized-ai/inferenced
    command: ["sh", "./init-docker.sh"]
    volumes:
      - .inference:/root/.inference
      - ./${GENESIS_FILE}:/root/genesis.json
    environment:
      - SEEDS=${SEEDS}
      - KEY_NAME=${KEY_NAME}
    ports:
      - "26656:26656" #p2p
      - "26657:26657" #rpc
  api:
    container_name: api
    image: gcr.io/decentralized-ai/api
    depends_on:
      - node
    environment:
      - KEY_NAME=${KEY_NAME}
      - DAPI_API__POC_CALLBACK_URL=${DAPI_API__POC_CALLBACK_URL}
      - PORT=${PORT}
    ports:
      - "${PORT}:8080"
    volumes:
      - .inference:/root/.inference
