services:
  node:
    container_name: node
    image: gcr.io/decentralized-ai/inferenced
    command: ["sh", "./init-docker-genesis.sh"]
    volumes:
      - .inference:/root/.inference
      - ./genesis-overrides.json:/root/genesis_overrides.json
    environment:
      - KEY_NAME=genesis
      - IS_GENESIS=true
    ports:
      - "26656:26656" #p2p
      - "26657:26657" #rpc
  api:
    container_name: api
    image: gcr.io/decentralized-ai/api
    volumes:
      - .inference:/root/.inference
      - ./node-config.json:/root/node_config.json
    depends_on:
      - node
    environment:
      - KEY_NAME=genesis
      - DAPI_API__POC_CALLBACK_URL=http://api:8080
      - DAPI_API__PUBLIC_URL=http://172.18.114.148:8000
      - IS_GENESIS=true
      - NODE_CONFIG_PATH=/root/node_config.json
    ports:
      - "8000:8080"
    restart: always

  inference-node:
    image: gcr.io/decentralized-ai/mlnode:3.0.0-alpha4
    volumes:
      - ${HOME}/cache:/root/.cache
    environment:
      - HF_HOME=/root/.cache
      - HF_HUB_ENABLE_HF_TRANSFER=true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      uvicorn api.app:app
      --host=0.0.0.0
      --port=8080
    restart: always
volumes:
  inference-data: