services:
  inference:
    image: ghcr.io/product-science/mlnode:3.0.3-alpha1
    command: >
      uvicorn api.app:app
      --host=0.0.0.0
      --port=8080
    environment:
      - HF_HOME=/root/.cache
    volumes:
      - /srv/dai/cache:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  genesis-network:
    driver: bridge
    external: true