services:
  node:
    image: ghcr.io/product-science/inferenced:0.0.1-alpha6
    command: ["sh", "./init-docker-genesis.sh"]
    environment:
      - KEY_NAME=genesis
      - SNAPSHOT_INTERVAL=1000
      - SNAPSHOT_KEEP_RECENT=5
    volumes:
      - /srv/dai/inference:/root/.inference
      - ./genesis-overrides.json:/root/genesis_overrides.json
    ports:
      - "26656:26656"
      - "26657:26657"

  api:
    image: ghcr.io/product-science/api:0.0.1-alpha6
    depends_on:
      - node
    environment:
      - KEY_NAME=genesis
      - DAPI_API__POC_CALLBACK_URL=http://10.0.0.3:8000
      - DAPI_API__PUBLIC_URL=http://195.242.10.196:8000
      - DAPI_CHAIN_NODE__IS_GENESIS=true
      - DAPI_CHAIN_NODE__URL=http://10.0.0.3:26657
      - NODE_CONFIG_PATH=/root/node_config.json
      - P2P_EXTERNAL_ADDRESS=tcp://195.242.10.196:26656
    volumes:
      - /srv/dai/inference:/root/.inference
      - ./node-config:/root/node_config.json
    ports:
      - "8000:8080"
