services:
  inference:
    image: gcr.io/decentralized-ai/mlnode:3.0.1-alpha1
    restart: always
    command: >
      uvicorn api.app:app
      --host=0.0.0.0
      --port=8080
    environment:
      - HF_HOME=/root/.cache
    volumes:
      - /srv/dai/cache:/root/.cache
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  genesis-network:
    driver: bridge
    external: true