services:
  node:
    container_name: node
    image: gcr.io/decentralized-ai/inferenced:7ae6909
    command: ["sh", "./init-docker-genesis.sh"]
    volumes:
      - .inference:/root/.inference
      - ./genesis-overrides.json:/root/genesis_overrides.json
    environment:
      - KEY_NAME=${KEY_NAME}
      - SNAPSHOT_INTERVAL=${SNAPSHOT_INTERVAL:-1000} # how often create state snapshots
      - SNAPSHOT_KEEP_RECENT=${SNAPSHOT_KEEP_RECENT:-5} # how many snapshots to keep
      - INIT_TGBOT=true
      - TGBOT_PRIVATE_KEY_PASS=${TGBOT_PRIVATE_KEY_PASS:-defaultpassword}
    ports:
      - "26656:26656" #p2p
      - "26657:26657" #rpc
  api:
    container_name: api
    image: gcr.io/decentralized-ai/api:7ae6909
    volumes:
      - .inference:/root/.inference
      - ./node-config.json:/root/node_config.json
    depends_on:
      - node
    environment:
      - KEY_NAME=${KEY_NAME}
      - DAPI_API__POC_CALLBACK_URL=${DAPI_API__POC_CALLBACK_URL}
      - DAPI_API__PUBLIC_URL=${PUBLIC_URL}
      - IS_GENESIS=true
      - NODE_CONFIG_PATH=/root/node_config.json
    ports:
      - "${PORT:-8080}:8080"
    restart: always

  inference-node:
    image: gcr.io/decentralized-ai/mlnode:latest
    volumes:
      - ${HOME}/cache:/root/.cache
    environment:
      - HF_HOME=/root/.cache
      - HF_HUB_ENABLE_HF_TRANSFER=true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      uvicorn api.app:app
      --host=0.0.0.0
      --port=8080
    restart: always