apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../join
  - worker3-node-config.yaml
  - worker3-overrides.yaml

patchesStrategicMerge:
  - |- # Patch for Node StatefulSet
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: node
    spec:
      template:
        spec:
          nodeSelector:
            kubernetes.io/hostname: k8s-worker-2

  - |- # Patch for Inference Deployment
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: inference
    spec:
      template:
        spec:
          nodeSelector:
            kubernetes.io/hostname: k8s-worker-2

# Patches for tmkms and api deployments if needed for this worker

# To also pin TMKMS and API deployments to k8s-worker-2, add similar patches:
#  - |-
#    apiVersion: apps/v1
#    kind: Deployment
#    metadata:
#      name: tmkms
#    spec:
#      template:
#        spec:
#          nodeSelector:
#            kubernetes.io/hostname: k8s-worker-2
#
#  - |-
#    apiVersion: apps/v1
#    kind: Deployment
#    metadata:
#      name: api
#    spec:
#      template:
#        spec:
#          nodeSelector:
#            kubernetes.io/hostname: k8s-worker-2 