apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      enableServiceLinks: false
      imagePullSecrets:
      - name: ghcr-credentials
      containers:
      - name: api
        image: ghcr.io/product-science/api:0.1.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
          name: public-api
        - containerPort: 9100
          name: ml-api
        - containerPort: 9200
          name: admin-api
        envFrom:
        - configMapRef:
            name: config
        env:
        - name: NODE_CONFIG_PATH
          value: "/root/node_config.json"
        volumeMounts:
        - name: inference-data
          mountPath: /root/.inference
        - name: node-config
          mountPath: /root/node_config.json
          subPath: node_config.json
      volumes:
      - name: inference-data # This volume is now a hostPath
        hostPath:
          path: /srv/dai/inference # Matches genesis setup
          type: DirectoryOrCreate
      - name: node-config
        configMap:
          name: node-config-cm
