apiVersion: v1
kind: ConfigMap
metadata:
  name: join-node-overrides
data:
  # Replace <...> placeholders with actual values for each worker
  # From config.env.template
  KEY_NAME: "<FILL_IN_KEY_NAME>"
  PUBLIC_URL: "http://<REPLACE_WITH_WORKER_PUBLIC_IP_OR_DNS>:<REPLACE_WITH_WORKER_API_PORT>"
  P2P_EXTERNAL_ADDRESS: "tcp://<REPLACE_WITH_WORKER_PUBLIC_IP_OR_DNS>:<REPLACE_WITH_WORKER_P2P_PORT>" # e.g., port 5000

  # Identical for all join workers
  NODE_CONFIG: "/etc/node-config/node-config.json" # Path where node-config.json will be mounted from the other ConfigMap
  SEED_API_URL: "http://34.9.136.116:30000"
  SEED_NODE_RPC_URL: "http://34.9.136.116:30002"
  SEED_NODE_P2P_URL: "tcp://34.9.136.116:30001"
  DAPI_API__POC_CALLBACK_URL: "http://api-private:9100"
  DAPI_CHAIN_NODE__URL: "http://node:26657"
  DAPI_CHAIN_NODE__P2P_URL: "http://node:26656"
  RPC_SERVER_URL_1: "http://34.9.136.116:30002"
  RPC_SERVER_URL_2: "http://34.9.136.116:30002"

  # Variables from docker-compose for node
  TRUSTED_BLOCK_PERIOD: "2000" # Default from docker-compose
  CONFIG_p2p__allow_duplicate_ip: "true"
  CONFIG_p2p__handshake_timeout: "30s"
  CONFIG_p2p__dial_timeout: "30s"
  TKMS_PORT: "26658" # Port node listens on for TMKMS

  # Additional for API service from docker-compose (if not already covered)
  DAPI_API__PUBLIC_SERVER_PORT: "9000" # Internal port for API service, API_PORT is for host exposure
  DAPI_API__ML_SERVER_PORT: "9100"
  DAPI_API__ADMIN_SERVER_PORT: "9200"
