apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference
  # namespace: <WORKER_NAMESPACE>
  labels:
    app: inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference
  template:
    metadata:
      labels:
        app: inference
    spec:
      enableServiceLinks: false
      nodeSelector:
        # kubernetes.io/hostname: <WORKER_NODE_HOSTNAME> # e.g., k8s-worker-2 - UNCOMMENT AND SET THIS
      hostIPC: true # Matches genesis
      # imagePullSecrets: # Add if your image is in a private registry
      # - name: ghcr-credentials
      containers:
      - name: inference
        image: ghcr.io/product-science/mlnode:3.0.4-alpha2
        imagePullPolicy: IfNotPresent
        command:
        - "/app/entrypoint.sh"
        - "uvicorn"
        - "api.app:app"
        - "--host=0.0.0.0"
        - "--port=8080"
        ports:
        - containerPort: 8080
          name: inference-api
        # Port 5000 was also in genesis inference deployment, let's include it for consistency.
        # If not used by join node's inference, it can be removed.
        - containerPort: 5000
          name: poc-api # Matches genesis deployment, role might be different for join node config
        envFrom:
        - configMapRef:
            name: join-node-overrides # For HF_HOME, HF_HUB_ENABLE_HF_TRANSFER
        env:
        # VLLM_ATTENTION_BACKEND was in genesis, add it here if still applicable
        # - name: VLLM_ATTENTION_BACKEND
        #   value: "FLASHINFER"
        resources:
          limits:
            nvidia.com/gpu: "1" # Request 1 GPU
        volumeMounts:
        - name: cache
          mountPath: /root/.cache # HF_HOME points to /mnt/shared, which is mounted here.
      volumes:
      - name: cache
        hostPath:
          path: /mnt/shared # Matches genesis; ensure this path exists on worker nodes
          type: DirectoryOrCreate
