apiVersion: v1
kind: ConfigMap
metadata:
  name: join-node-settings # This name will be used to mount the config
  # namespace: <WORKER_NAMESPACE> # Will be applied with -n flag
data:
  node-config.json: |
    [
      {
        "id": "node1",
        "host": "inference",
        "inference_port": 5000,
        "poc_port": 8080,
        "max_concurrent": 500,
        "models": {
          "Qwen/Qwen2.5-7B-Instruct": {
            "args": [
              "--quantization",
              "fp8"
            ]
          }
        }
      }
    ]
