apiVersion: v1
kind: ConfigMap
metadata:
  name: join-node-overrides # This name will be used by pods
  # namespace: <WORKER_NAMESPACE> # Will be applied with -n flag
data:
  # Replace <...> placeholders with actual values for each worker
  # From config.env.template
  KEY_NAME: "<FILL_IN_KEY_NAME>"
  API_PORT: "<REPLACE_WITH_WORKER_API_PORT>" # e.g., "8001" for worker 2, "8002" for worker 3
  PUBLIC_URL: "http://<REPLACE_WITH_WORKER_PUBLIC_IP_OR_DNS>:<REPLACE_WITH_WORKER_API_PORT>"
  P2P_EXTERNAL_ADDRESS: "tcp://<REPLACE_WITH_WORKER_PUBLIC_IP_OR_DNS>:<REPLACE_WITH_WORKER_P2P_PORT>" # e.g., port 5000
  NODE_CONFIG: "/etc/node-config/node-config.json" # Path where node-config.json will be mounted from the other ConfigMap
  HF_HOME: "/mnt/shared" # Matches genesis and docker-compose intent

  # These seem like global values, but can be overridden per worker if needed
  SEED_API_URL: "http://36.189.234.237:19250"
  SEED_NODE_RPC_URL: "http://172.18.114.125:26657"
  SEED_NODE_P2P_URL: "tcp://36.189.234.237:19249" # Make sure genesis node p2p is reachable at this address
  DAPI_API__POC_CALLBACK_URL: "http://api:9100" # Internal service communication
  DAPI_CHAIN_NODE__URL: "http://node:26657" # Internal service communication
  DAPI_CHAIN_NODE__P2P_URL: "http://node:26656" # Internal service communication
  RPC_SERVER_URL_1: "http://172.18.114.125:26657"
  RPC_SERVER_URL_2: "http://172.18.114.125:26657"

  # Variables from docker-compose for node
  TRUSTED_BLOCK_PERIOD: "2000" # Default from docker-compose
  CONFIG_p2p__allow_duplicate_ip: "true"
  CONFIG_p2p__handshake_timeout: "30s"
  CONFIG_p2p__dial_timeout: "30s"
  TKMS_PORT: "26658" # Port node listens on for TMKMS

  # Additional for API service from docker-compose (if not already covered)
  # DAPI_API__PUBLIC_URL is covered by PUBLIC_URL
  # DAPI_CHAIN_NODE__SEED_API_URL is covered by SEED_API_URL
  # DAPI_CHAIN_NODE__URL is DAPI_CHAIN_NODE__URL
  # DAPI_CHAIN_NODE__P2P_URL is DAPI_CHAIN_NODE__P2P_URL
  # NODE_CONFIG_PATH is covered by NODE_CONFIG
  DAPI_API__PUBLIC_SERVER_PORT: "9000" # Internal port for API service, API_PORT is for host exposure
  DAPI_API__ML_SERVER_PORT: "9100"
  DAPI_API__ADMIN_SERVER_PORT: "9200"

  # Additional for Inference service from docker-compose
  # HF_HOME is already defined
  HF_HUB_ENABLE_HF_TRANSFER: "true"
