apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - node-statefulset.yaml
  - ../common/node-service.yaml
  - api-deployment.yaml
  - ../common/api-private-service.yaml
  - ../common/api-public-service.yaml
  - inference-deployment.yaml
  - ../common/inference-service.yaml
  - tmkms-deployment.yaml
  - tmkms-pvc.yaml
  - ../common/tmkms-service.yaml

  # ML node config
  - ../common/node-configs/node-config-configmap.yaml

# The actual ConfigMaps (join-node-settings and join-node-overrides)
# will be provided by the overlays, not from the base templates.
# The .template.yaml files in this directory are for user reference only.
