apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: node
  # namespace: <WORKER_NAMESPACE>
  labels:
    app: node
spec:
  serviceName: "node"
  replicas: 1 # Typically 1 for a specific join node identity
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      enableServiceLinks: false
      nodeSelector:
        # kubernetes.io/hostname: <WORKER_NODE_HOSTNAME> # e.g., k8s-worker-2 - UNCOMMENT AND SET THIS
      # imagePullSecrets: # Add if your image is in a private registry
      # - name: ghcr-credentials
      containers:
      - name: node
        image: ghcr.io/product-science/inferenced:0.1.2
        imagePullPolicy: IfNotPresent
        command:
        - "sh"
        - "-c"
        - "./init-docker.sh" # Assuming this script is in the image's WORKDIR/PATH
        ports:
        - containerPort: 26656
          name: tendermint-p2p
        - containerPort: 26657
          name: tendermint-rpc
        - containerPort: 26658
          name: tmkms
        envFrom:
        - configMapRef:
            name: join-node-overrides # From join-overrides-configmap.template.yaml
        volumeMounts:
        - name: inference-data
          mountPath: /root/.inference # Shared data with API
        - name: node-config-volume
          mountPath: /etc/node-config # Mount dir for node-config.json
      volumes:
      - name: inference-data # This volume is now a hostPath
        hostPath:
          path: /srv/dai/inference # Matches genesis setup
          type: DirectoryOrCreate
      - name: node-config-volume
        configMap:
          name: join-node-settings # From join-node-config-configmap.template.yaml
          items:
          - key: node-config.json
            path: node-config.json
