apiVersion: apps/v1
kind: Deployment
metadata:
  name: tmkms
  labels:
    app: tmkms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tmkms
  template:
    metadata:
      labels:
        app: tmkms
    spec:
      enableServiceLinks: false
      imagePullSecrets:
      - name: ghcr-credentials
      initContainers:
      - name: init-tmkms-data
        image: ghcr.io/product-science/tmkms-softsign-with-keygen:0.1.2
        command: ["sh", "-c", "if [ ! -f /root/stage-dir/config.toml ]; then echo 'Initializing tmkms data volume...'; cp -r /root/.tmkms/. /root/stage-dir/; else echo 'tmkms data volume already initialized.'; fi"]
        volumeMounts:
        - name: tmkms-data
          mountPath: /root/stage-dir
      containers:
      - name: tmkms
        image: ghcr.io/product-science/tmkms-softsign-with-keygen:0.1.2
        imagePullPolicy: IfNotPresent
        env:
        - name: VALIDATOR_LISTEN_ADDRESS
          value: "tcp://node:26658"
        ports:
        - containerPort: 26658 # Though tmkms connects out, its good practice to declare if it also listens on a port, even if not exposed via service
                               # The docker-compose doesn't explicitly expose a port for tmkms itself.
        volumeMounts:
        - name: tmkms-data
          mountPath: /root/.tmkms
      volumes:
      - name: tmkms-data
        persistentVolumeClaim:
          claimName: tmkms-data-pvc
