apiVersion: v1
kind: Service
metadata:
  name: api-public
  labels:
    app: api
spec:
  type: NodePort
  selector:
    app: api
  ports:
  - name: public
    port: 9000
    targetPort: 9000
    nodePort: 30000
