apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # ConfigMaps specific to Genesis
  - config.yaml
  - genesis-overrides-configmap.yaml

  # Workloads specific to Genesis
  - node-statefulset.yaml
  - api-deployment.yaml
  - inference-deployment.yaml

  # Common Services
  - ../common/api-private-service.yaml
  - ../common/api-public-service.yaml
  - ../common/node-service.yaml
  - ../common/inference-service.yaml
  - ../common/tmkms-service.yaml

  # ML node config
  - ../common/node-configs/node-config-configmap.yaml
