apiVersion: v1
kind: Service
metadata:
  name: node
  labels:
    app: node
spec:
  type: NodePort
  selector:
    app: node
  ports:
  - name: rpc
    port: 26656
    targetPort: 26656
    nodePort: 30000
  - name: p2p
    port: 26657
    targetPort: 26657
    nodePort: 30001
  - name: tmkms
    port: 26658
    targetPort: 26658
    nodePort: 30005 # For tmkms communication 